/**
 * Auto-generated from crawl/crawl crawl-ref/source/spl-data.h — do not edit by hand.
 * Regenerate: `node scripts/generate-spell-levels.mjs`
 */
export const DCSS_SPELL_LEVEL_BY_EXACT_NAME: Record<string, 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9> = {
  "Cause Fear": 4,
  "Magic Dart": 1,
  "Fireball": 5,
  "Apportation": 1,
  "Volatile Blastmotes": 3,
  "Dig": 4,
  "Bolt of Fire": 6,
  "Bolt of Cold": 6,
  "Lightning Bolt": 5,
  "Arcjolt": 5,
  "Plasma Beam": 6,
  "Permafrost Eruption": 6,
  "Vhi's Electrolunge": 4,
  "Bolt of Magma": 5,
  "Slow": 1,
  "Haste": 6,
  "Petrify": 4,
  "Invisibility": 6,
  "Throw Flame": 2,
  "Throw Frost": 2,
  "Disjunction": 8,
  "Freezing Cloud": 5,
  "Freezing Gust": 5,
  "Mephitic Cloud": 3,
  "Venom Bolt": 5,
  "Olgreb's Toxic Radiance": 4,
  "Teleport Other": 3,
  "Death's Door": 9,
  "Mass Confusion": 6,
  "Smiting": 4,
  "Summon Small Mammal": 1,
  "Abjuration": 3,
  "Bolt of Draining": 5,
  "Lehudib's Crystal Spear": 8,
  "Polar Vortex": 9,
  "Poisonous Cloud": 5,
  "Fire Storm": 9,
  "Call Down Damnation": 9,
  "Call Down Lightning": 4,
  "Blink": 2,
  "Blink Away": 2,
  "Blink Close": 2,
  "Iskenderun's Mystic Blast": 4,
  "Summon Horrible Things": 8,
  "Malign Gateway": 7,
  "Animate Dead": 4,
  "Vampiric Draining": 3,
  "Haunt": 7,
  "Martyr's Knell": 4,
  "Borgnjor's Revivification": 8,
  "Freeze": 1,
  "Ozocubu's Refrigeration": 7,
  "Sticky Flame": 4,
  "Summon Ice Beast": 3,
  "Ozocubu's Armour": 3,
  "Call Imp": 2,
  "Deflect Missiles": 6,
  "Berserker Rage": 3,
  "Dispel Undead": 4,
  "Poison Arrow": 6,
  "Sting": 1,
  "Sublimation of Blood": 2,
  "Cigotuvi's Putrefaction": 4,
  "Iron Shot": 6,
  "Bombard": 6,
  "Stone Arrow": 3,
  "Shock": 1,
  "Swiftness": 3,
  "Debugging Ray": 7,
  "Death Channel": 6,
  "Symbol of Torment": 6,
  "Siphon Essence": 7,
  "Throw Icicle": 4,
  "Airstrike": 4,
  "Momentum Strike": 2,
  "Shadow Creatures": 6,
  "Confusing Touch": 3,
  "Passwall": 3,
  "Ignite Poison": 4,
  "Call Canine Familiar": 3,
  "Metabolic Englaciation": 5,
  "Silence": 5,
  "Shatter": 9,
  "Dispersal": 6,
  "Static Discharge": 2,
  "Alistair's Intoxication": 5,
  "Lee's Rapid Deconstruction": 5,
  "Conjure Ball Lightning": 6,
  "Chain Lightning": 9,
  "Portal Projectile": 3,
  "Monstrous Menagerie": 7,
  "Passage of Golubria": 4,
  "Fulminant Prism": 4,
  "Minor Healing": 2,
  "Major Healing": 6,
  "Woodweal": 4,
  "Brain Bite": 3,
  "Steam Ball": 4,
  "Ufetubi Swarm": 4,
  "Summon Sin Beast": 4,
  "Bolt of Devastation": 5,
  "Summon Undead": 7,
  "Cantrip": 1,
  "Quicksilver Bolt": 5,
  "Metal Splinters": 5,
  "Splinterspray": 4,
  "Summon Drakes": 6,
  "Blink Other Close": 2,
  "Summon Mushrooms": 4,
  "Caustic Breath": 5,
  "Pyre Arrow": 4,
  "Glacial Breath": 5,
  "Summon Water Elementals": 5,
  "Spawn Tentacles": 5,
  "Summon Eyeballs": 5,
  "Summon Earth Elementals": 5,
  "Summon Air Elementals": 5,
  "Summon Fire Elementals": 5,
  "Mara Summon": 5,
  "Summon Illusion": 5,
  "Primal Wave": 6,
  "Call Tide": 7,
  "Orb of Destruction": 7,
  "Ink Cloud": 7,
  "Might": 3,
  "Might Other": 5,
  "Awaken Forest": 6,
  "Druid's Call": 6,
  "Brothers in Arms": 6,
  "Trog's Hand": 3,
  "Summon Mortal Champion": 7,
  "Vanquished Vanguard": 4,
  "Summon Holies": 5,
  "Holy Flames": 7,
  "Injury Mirror": 4,
  "Drain Life": 6,
  "Leda's Liquefaction": 4,
  "Summon Hydra": 7,
  "Mesmerise": 5,
  "Hellfire Court": 8,
  "Petrifying Cloud": 5,
  "Inner Flame": 3,
  "Ensnare": 6,
  "Greater Ensnare": 6,
  "Thunderbolt": 2,
  "Iskenderun's Battlesphere": 4,
  "Summon Minor Demon": 2,
  "Sticks to Snakes": 2,
  "Gloom": 3,
  "Beckoning Gale": 3,
  "Force Lance": 4,
  "Word of Recall": 3,
  "Injury Bond": 5,
  "Spectral Cloud": 5,
  "Call Lost Souls": 5,
  "Blink Allies Encircling": 6,
  "Awaken Vines": 6,
  "Volley of Thorns": 4,
  "Cage of Brambles": 5,
  "Waterstrike": 4,
  "Wind Blast": 3,
  "Fugue of the Fallen": 3,
  "Summon Vermin": 5,
  "Malign Offering": 5,
  "Searing Ray": 2,
  "Discord": 8,
  "Invisibility Other": 6,
  "Orb of Electricity": 7,
  "Flash Freeze": 7,
  "Creeping Frost": 5,
  "Legendary Destruction": 8,
  "Forceful Invitation": 4,
  "Plane Rend": 8,
  "Chain of Chaos": 8,
  "Call of Chaos": 7,
  "Sign of Ruin": 7,
  "Sap Magic": 5,
  "Blink Allies Away": 6,
  "Summon Forest": 5,
  "Forge Lightning Spire": 4,
  "Forge Blazeheart Golem": 4,
  "Rebounding Blaze": 7,
  "Rebounding Chill": 7,
  "Glaciate": 9,
  "Dragon's Call": 9,
  "Spellspark Servitor": 7,
  "Summon Mana Viper": 5,
  "Phantom Mirror": 5,
  "Diminish Spells": 3,
  "Corrosive Bolt": 6,
  "Bolt of Light": 6,
  "Awaken Flesh": 6,
  "Summon Emperor Scorpions": 7,
  "Irradiate": 5,
  "Battlecry": 6,
  "Warning Cry": 6,
  "Hunting Call": 6,
  "Funeral Dirge": 4,
  "Seal Doors": 6,
  "Flay": 4,
  "Berserk Other": 3,
  "Corrupting Pulse": 6,
  "Siren Song": 5,
  "Avatar Song": 7,
  "Paralysis Gaze": 4,
  "Confusion Gaze": 3,
  "Antimagic Gaze": 5,
  "Draining Gaze": 4,
  "Weakening Gaze": 4,
  "Mourning Wail": 3,
  "Death Rattle": 7,
  "March of Sorrows": 7,
  "Summon Scarabs": 7,
  "Throw Ally": 2,
  "Cleansing Flame": 8,
  "Gell's Gravitas": 3,
  "Yara's Violent Unravelling": 5,
  "Entropic Weave": 5,
  "Summon Executioners": 9,
  "Oblivion Howl": 3,
  "Prayer of Brilliance": 5,
  "Iceblast": 5,
  "Slug Dart": 1,
  "Fleetfoot": 2,
  "Infernal Servant": 7,
  "Bind Souls": 6,
  "Infestation": 8,
  "Still Winds": 6,
  "Resonance Strike": 5,
  "Ghostly Sacrifice": 7,
  "Dream Dust": 3,
  "Lesser Beckoning": 2,
  "Upheaval": 5,
  "Mercury Arrow": 2,
  "Poisonous Vapours": 1,
  "Ignition": 8,
  "Borgnjor's Vile Clutch": 5,
  "Fastroot": 5,
  "Warp Space": 5,
  "Sojourning Bolt": 6,
  "Harpoon Shot": 4,
  "Grasping Roots": 5,
  "Throw Bolas": 4,
  "Throw Klown Pie": 5,
  "Sporulate": 5,
  "Launch Sporangium": 5,
  "Starburst": 6,
  "Foxfire": 1,
  "Marshlight": 4,
  "Hailstorm": 3,
  "Eringya's Noxious Bog": 6,
  "Dispel Undead Range": 5,
  "Frozen Ramparts": 3,
  "Maxwell's Capacitive Coupling": 8,
  "Roll": 5,
  "Hurl Sludge": 6,
  "Summon Tzitzimitl": 8,
  "Summon Hell Sentinel": 8,
  "Awaken Armour": 4,
  "Manifold Assault": 7,
  "Eruption": 5,
  "Pyroclastic Surge": 5,
  "Stunning Burst": 4,
  "Corrupt": 7,
  "Conjure Living Spells": 6,
  "Summon Cactus Giant": 6,
  "Stoke Flames": 8,
  "Seracfall": 5,
  "Scorch": 2,
  "Flame Wave": 4,
  "Enfeeble": 7,
  "Summon Spiders": 6,
  "Anguish": 4,
  "Summon Scorpions": 4,
  "Sheza's Dance": 5,
  "Divine Armament": 4,
  "Kiss of Death": 1,
  "Jinxbite": 2,
  "Sigil of Binding": 3,
  "Dimensional Bullseye": 4,
  "Brom's Barrelling Boulder": 4,
  "Vitrifying Gaze": 6,
  "Crystallising Shot": 6,
  "Tremorstone": 2,
  "Regenerate Other": 4,
  "Mass Regeneration": 7,
  "Noxious Breath": 5,
  "Unleash Destruction": 3,
  "Hurl Torchlight": 4,
  "Combustion Breath": 5,
  "Nullifying Breath": 5,
  "Steam Breath": 4,
  "Mud Breath": 5,
  "Galvanic Breath": 5,
  "Maxwell's Portable Piledriver": 3,
  "Gell's Gavotte": 6,
  "Fulsome Fusillade": 8,
  "Hoarfrost Cannonade": 5,
  "Seismic Stomp": 5,
  "Hoarfrost Bullet": 5,
  "Flashing Balestra": 5,
  "Phantom Blitz": 7,
  "Bestow Arms": 5,
  "Hellfire Mortar": 7,
  "Creeping Shadow": 5,
  "Shadow Tempest": 5,
  "Shadow Prism": 5,
  "Shadow Puppet": 5,
  "Shadow Turret": 5,
  "Shadow Bind": 5,
  "Shadow Draining": 5,
  "Grave Claw": 2,
  "Launch Clockwork Bee": 3,
  "Construct Spike Launcher": 2,
  "Kinetic Grapnel": 1,
  "Diamond Sawblades": 7,
  "Shred": 1,
  "Eringya's Surprising Crocodile": 4,
  "Platinum Paragon": 9,
  "Alistair's Walking Alembic": 5,
  "Forge Monarch Bomb": 6,
  "Launch Bomblet": 6,
  "Splinterfrost Shell": 7,
  "Nazja's Percussive Tempering": 5,
  "Fortress Blast": 6,
  "Summon Seismosaurus Egg": 4,
  "Forge Phalanx Beetle": 6,
  "Rending Blade": 4,
  "Magma Barrage": 5,
  "Dominate Undead": 6,
  "Detonation Catalyst": 5,
  "Rust Breath": 5,
  "Golden Breath": 5,
  "Sphinx Sisters": 7,
  "Ill Omen": 4,
  "Doom Bolt": 5,
  "Ostracise": 7,
  "Mutagenic Gaze": 5,
  "Acid Ball": 5,
  "Doomsaying": 6,
  "Sleetstrike": 5,
  "Landbreaker": 5,
}
